const _single_person_conversation_webhook_request_body = {
  accountEmail: 'cocomo',
  content: 'I am taking some time to rethink certain features in the product',
  is_outbound: false,
  status: 'RECEIVED',
  error_code: null,
  error_message: null,
  error_reason: null,
  message_handle: '41B55342-CE1D-4996-9B86-0AB5D8232700',
  date_sent: '2026-03-12T18:40:36.100Z',
  date_updated: '2026-03-12T18:40:36.104Z',
  from_number: '+918002594916',
  number: '<sender_number>',
  to_number: '<sayla_number>',
  was_downgraded: null,
  plan: '<free_api | dedicated>',
  media_url: '',
  message_type: 'message',
  group_id: '',
  participants: [],
  send_style: '',
  opted_out: false,
  error_detail: null,
  sendblue_number: '<sendblue_number>',
  service: 'iMessage',
  group_display_name: null,
};

const _group_conversation_webhook_request_body = {
  accountEmail: 'cocomo',
  content: 'Hey sayla',
  is_outbound: false,
  status: 'RECEIVED',
  error_code: null,
  error_message: null,
  error_reason: null,
  message_handle: '3592B6C0-4AE2-41AD-875D-7DDAEF287D79',
  date_sent: '2026-03-12T23:06:06.998Z',
  date_updated: '2026-03-12T23:06:07.007Z',
  from_number: '<from_phone_number>',
  number: '<sender_number>',
  to_number: '<other_person_number>',
  was_downgraded: null,
  plan: 'dedicated',
  media_url: '',
  message_type: 'group',
  group_id: 'sb_group_<something>',
  participants: ['<first_phone_number>', '<second_phone_number>', '...'],
  send_style: '',
  opted_out: false,
  error_detail: null,
  sendblue_number: '<sendblue_number>',
  service: 'iMessage',
  group_display_name: null,
};
